//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class g_StockEntities : DbContext
    {
        public g_StockEntities()
            : base("name=g_StockEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Action> Action { get; set; }
        public virtual DbSet<Armoire> Armoire { get; set; }
        public virtual DbSet<Article_CodeBarre> Article_CodeBarre { get; set; }
        public virtual DbSet<Article_Info> Article_Info { get; set; }
        public virtual DbSet<Article_Photo> Article_Photo { get; set; }
        public virtual DbSet<Article_Reference> Article_Reference { get; set; }
        public virtual DbSet<BL> BL { get; set; }
        public virtual DbSet<BL_Article> BL_Article { get; set; }
        public virtual DbSet<Emplacement> Emplacement { get; set; }
        public virtual DbSet<Famille> Famille { get; set; }
        public virtual DbSet<Fournisseur> Fournisseur { get; set; }
        public virtual DbSet<Magasin> Magasin { get; set; }
        public virtual DbSet<Mouvement> Mouvement { get; set; }
        public virtual DbSet<Profil> Profil { get; set; }
        public virtual DbSet<Rayonnage> Rayonnage { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<Unite> Unite { get; set; }
        public virtual DbSet<Unite_Mesure> Unite_Mesure { get; set; }
        public virtual DbSet<Unite_Type> Unite_Type { get; set; }
        public virtual DbSet<Utilisateur> Utilisateur { get; set; }
    }
}
